### ISSUE TITLE
처음 deck에서 꺼냈을 때 

### ISSUE THREAD

**Issue by Changha-dev** [SE-2023-SeoulTech-Team1/UnoGame#6]
def flip_deck_card(self, flip_card):
        global openned_cards, card_loc, timerFlag

        # game의 pick_current_card 사용해서 게임 시작 직후 current card 정보 불러오고 open된 카드 리스트에 저장
        if flip_card is True:
            openned_cards = []
            self.game.pick_current_card()
            openned_cards.append(self.game.current_card)
            self.card_move_sound.play()
            print(f"\n현재 뒤집어진 카드는 {self.game.current_card} 입니다.")

            # 카드의 현재 위치 저장
            card_loc = self.screen_width * 0.25
            flip_card = False

        # 오픈된 카드 목표 위치
        top = self.screen_height * 0.25
        left = self.screen_width * 0.4

        # 카드 목표 위치 도달까지 위치 변경
        if card_loc <= left:
            card_loc += 10
            draw_card_front(self.screen, openned_cards[-1], top, card_loc)
        else:
            draw_card_front(self.screen, openned_cards[-1], top, card_loc)

            if self.timerFlag == True:
                self.timer(self.timerFlag, TIMEOUT)
            self.timerFlag = True

처음 나온 카드가 기능 카드인 경우가 발생해서 고쳐야 할 오류인것 같습니다!

**Comment by EhanSohn** [comment]
수정됐습니다.
